import { useEffect, useMemo, useState } from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import { Megaphone, Pin, Shield, UserPlus, Users, X } from 'lucide-react';
import { makeSupabase } from './lib/supabase';
import { createChatKey, decryptText, encryptText, exportKey, importKey } from './lib/crypto';
import { getOrCreateIdentity, unwrapChatKey, wrapChatKey } from './lib/crypto-keys';

type Member={auth0_sub:string;display_name:string;user_code:string;role:'owner'|'admin'|'member';removed_at?:string|null;encrypted_key:string;key_sender_public:JsonWebKey};
type Group={id:string;name:string;icon:string;members:Member[]};
type Invite={id:string;code:string;max_uses:number;uses:number;expires_at:string|null};
type Request={id:string;chat_id:string;requester_sub:string;status:string;created_at:string;profile?:{display_name:string;user_code:string;public_key:JsonWebKey}|null};
type PinRow={message_id:string;created_at:string;ciphertext:string|null;message_type:'text'|'file';pinned_by:string};
type Announcement={id:string;ciphertext:string;created_at:string;created_by:string};

const makeCode=()=>Array.from(crypto.getRandomValues(new Uint8Array(8)),x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%30]).join('');

export default function GroupManagementOverlay(){
 const {isAuthenticated,user,getIdTokenClaims}=useAuth0();
 const supabase=useMemo(()=>isAuthenticated?makeSupabase(async()=>(await getIdTokenClaims())?.__raw):null,[getIdTokenClaims,isAuthenticated]);
 const [open,setOpen]=useState(false),[groups,setGroups]=useState<Group[]>([]),[selectedId,setSelectedId]=useState(''),[tab,setTab]=useState<'members'|'customize'|'invites'|'pins'|'announcements'>('members');
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[memberCode,setMemberCode]=useState(''),[newName,setNewName]=useState(''),[newIcon,setNewIcon]=useState(''),[maxUses,setMaxUses]=useState('10'),[expires,setExpires]=useState(''),[inviteCode,setInviteCode]=useState(''),[announcement,setAnnouncement]=useState('');
 const [invites,setInvites]=useState<Invite[]>([]),[requests,setRequests]=useState<Request[]>([]),[pins,setPins]=useState<PinRow[]>([]),[announcements,setAnnouncements]=useState<Announcement[]>([]),[pinCandidates,setPinCandidates]=useState<PinRow[]>([]);
 const group=groups.find(x=>x.id===selectedId)||null;
 const me=group?.members.find(x=>x.auth0_sub===user?.sub);
 const isAdmin=me?.role==='owner'||me?.role==='admin';

 useEffect(()=>{if(!isAuthenticated)return;const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='g'){e.preventDefault();setOpen(true);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[isAuthenticated]);
 useEffect(()=>{if(open&&supabase&&user?.sub)void loadGroups();},[open,supabase,user?.sub]);
 useEffect(()=>{if(group){setNewName(group.name);setNewIcon(group.icon);void loadGroupData(group.id);}},[selectedId]);

 async function loadGroups(){if(!supabase||!user?.sub)return;const {data}=await supabase.from('chat_members').select('chat_id,chats(id,name,icon,chat_members(auth0_sub,display_name,user_code,role,removed_at,encrypted_key,key_sender_public))').eq('auth0_sub',user.sub).is('removed_at',null);const next=(data??[]).map((r:any)=>({id:r.chat_id,name:r.chats?.name||'Group',icon:r.chats?.icon||'👥',members:(r.chats?.chat_members??[]).filter((m:any)=>!m.removed_at)})).filter((g:any)=>g.members.length>2);setGroups(next);if(!selectedId&&next[0])setSelectedId(next[0].id);if(selectedId&&!next.some((g:any)=>g.id===selectedId))setSelectedId(next[0]?.id||'');}
 async function loadGroupData(chatId:string){if(!supabase||!user?.sub)return;setNotice('');const [i,r,p,a]=await Promise.all([supabase.from('group_invites').select('id,code,max_uses,uses,expires_at').eq('chat_id',chatId).order('created_at',{ascending:false}),supabase.from('group_join_requests').select('id,chat_id,requester_sub,status,created_at').eq('chat_id',chatId).eq('status','pending').order('created_at',{ascending:true}),supabase.from('pinned_messages').select('message_id,created_at,pinned_by,messages(ciphertext,message_type,created_at)').eq('chat_id',chatId).order('created_at',{ascending:false}),supabase.from('group_announcements').select('id,ciphertext,created_at,created_by').eq('chat_id',chatId).order('created_at',{ascending:false})]);setInvites((i.data??[]) as Invite[]);setPins((p.data??[]).map((x:any)=>({message_id:x.message_id,created_at:x.messages?.created_at??x.created_at,ciphertext:x.messages?.ciphertext??null,message_type:x.messages?.message_type??'text',pinned_by:x.pinned_by})));setAnnouncements((a.data??[]) as Announcement[]);const rawReq=(r.data??[]) as Request[];if(rawReq.length){const ids=rawReq.map(x=>x.requester_sub);const {data:profiles}=await supabase.from('profiles').select('auth0_sub,display_name,user_code,public_key').in('auth0_sub',ids);setRequests(rawReq.map(x=>({...x,profile:(profiles??[]).find((p:any)=>p.auth0_sub===x.requester_sub)||null})));}else setRequests([]);await loadPinCandidates(chatId);}
 async function loadPinCandidates(chatId:string){if(!supabase)return;const {data}=await supabase.from('messages').select('id,ciphertext,message_type,created_at').eq('chat_id',chatId).order('created_at',{ascending:false}).limit(40);const {data:p}=await supabase.from('pinned_messages').select('message_id').eq('chat_id',chatId);const pinned=new Set((p??[]).map((x:any)=>x.message_id));setPinCandidates((data??[]).filter((x:any)=>x.message_type==='text').map((x:any)=>({...x,pinned_by:pinned.has(x.id)?'pinned':''})) as PinRow[]);}
 async function groupKey(chatId:string){if(!supabase||!user?.sub)throw new Error('Not authenticated');const identity=await getOrCreateIdentity();const {data,error}=await supabase.from('chat_members').select('encrypted_key,key_sender_public').eq('chat_id',chatId).eq('auth0_sub',user.sub).single();if(error||!data)throw error??new Error('Could not load group key');return importKey(await unwrapChatKey(data.encrypted_key,identity.privateKey,data.key_sender_public));}
 async function saveName(){if(!group||!supabase)return;setBusy(true);try{const {error}=await supabase.rpc('set_group_name',{target_chat_id:group.id,target_name:newName});if(error)throw error;await loadGroups();setNotice('Group name updated.');}catch(e){setNotice(e instanceof Error?e.message:'Could not update name.');}finally{setBusy(false);}}
 async function saveIcon(){if(!group||!supabase)return;setBusy(true);try{const {error}=await supabase.rpc('set_group_icon',{target_chat_id:group.id,target_icon:newIcon});if(error)throw error;await loadGroups();setNotice('Group icon updated.');}catch(e){setNotice(e instanceof Error?e.message:'Could not update icon.');}finally{setBusy(false);}}
 async function addMember(){if(!group||!supabase||!isAdmin)return;const code=memberCode.trim();if(!code)return;setBusy(true);try{const {data:target,error}=await supabase.from('profiles').select('auth0_sub,display_name,user_code,public_key').eq('user_code',code).maybeSingle();if(error||!target)throw new Error('User not found.');if(group.members.some(m=>m.auth0_sub===target.auth0_sub))throw new Error('That user is already in the group.');const key=await groupKey(group.id),raw=await exportKey(key),identity=await getOrCreateIdentity(),wrapped=await wrapChatKey(raw,identity.privateKey,target.public_key);const {error:e}=await supabase.rpc('add_group_member',{target_chat_id:group.id,target_sub:target.auth0_sub,target_display_name:target.display_name,target_user_code:target.user_code,target_encrypted_key:wrapped,target_key_sender_public:identity.publicJwk});if(e)throw e;setMemberCode('');await loadGroups();setNotice('Member added.');}catch(e){setNotice(e instanceof Error?e.message:'Could not add member.');}finally{setBusy(false);}}
 async function removeMember(member:Member){if(!group||!supabase||!isAdmin||member.role==='owner')return;if(!confirm(`Remove ${member.display_name||member.user_code} from this group?`))return;const {error}=await supabase.rpc('remove_group_member',{target_chat_id:group.id,target_sub:member.auth0_sub});if(error)setNotice(error.message);else{await loadGroups();setNotice('Member removed.');}}
 async function setRole(member:Member,role:'admin'|'member'){if(!group||!supabase||!isAdmin||member.role==='owner')return;const {error}=await supabase.from('chat_members').update({role}).eq('chat_id',group.id).eq('auth0_sub',member.auth0_sub);if(error)setNotice(error.message);else await loadGroups();}
 async function createInvite(){if(!group||!supabase||!isAdmin)return;setBusy(true);try{const code=makeCode(),exp=expires?new Date(expires).toISOString():null;const {data,error}=await supabase.rpc('create_group_invite',{target_chat_id:group.id,target_code:code,target_max_uses:Math.max(1,Number(maxUses)||10),target_expires_at:exp});if(error)throw error;setInviteCode(data?.code||code);await loadGroupData(group.id);}catch(e){setNotice(e instanceof Error?e.message:'Could not create invite.');}finally{setBusy(false);}}
 async function requestJoin(){if(!supabase||!inviteCode.trim())return;setBusy(true);try{const {error}=await supabase.rpc('request_group_join',{target_code:inviteCode.trim()});if(error)throw error;setInviteCode('');setNotice('Join request sent. An admin must approve it.');}catch(e){setNotice(e instanceof Error?e.message:'Could not send request.');}finally{setBusy(false);}}
 async function resolveRequest(req:Request,approve:boolean){if(!group||!supabase||!isAdmin)return;setBusy(true);try{let wrapped='',senderPublic:JsonWebKey|null=null;if(approve){if(!req.profile)throw new Error('Requester profile unavailable.');const key=await groupKey(group.id),raw=await exportKey(key),identity=await getOrCreateIdentity();wrapped=await wrapChatKey(raw,identity.privateKey,req.profile.public_key);senderPublic=identity.publicJwk;}const {error}=await supabase.rpc('resolve_group_join_request',{target_request_id:req.id,approve,target_encrypted_key:wrapped,target_key_sender_public:senderPublic});if(error)throw error;await loadGroups();await loadGroupData(group.id);setNotice(approve?'Member approved.':'Request rejected.');}catch(e){setNotice(e instanceof Error?e.message:'Could not resolve request.');}finally{setBusy(false);}}
 async function togglePin(row:PinRow){if(!group||!supabase||!isAdmin)return;const fn=row.pinned_by?'unpin_group_message':'pin_group_message';const {error}=await supabase.rpc(fn,{target_chat_id:group.id,target_message_id:row.message_id});if(error)setNotice(error.message);else await loadGroupData(group.id);}
 async function postAnnouncement(){if(!group||!supabase||!isAdmin||!announcement.trim())return;setBusy(true);try{const key=await groupKey(group.id),ciphertext=await encryptText(announcement.trim(),key),{error}=await supabase.from('group_announcements').insert({chat_id:group.id,ciphertext,created_by:user?.sub});if(error)throw error;setAnnouncement('');await loadGroupData(group.id);}catch(e){setNotice(e instanceof Error?e.message:'Could not post announcement.');}finally{setBusy(false);}}
 async function decryptAnnouncement(row:Announcement){try{return await decryptText(row.ciphertext,await groupKey(group!.id));}catch{return '[Unable to decrypt on this device]';}}
 if(!isAuthenticated||!open)return isAuthenticated?<button className="group-tools-trigger" onClick={()=>setOpen(true)} title="Group tools"> <Users size={18}/> </button>:null;
 return <>
  <button className="group-tools-trigger" onClick={()=>setOpen(true)} title="Group tools"><Users size={18}/></button>
  <div className="group-tools-backdrop" onClick={()=>setOpen(false)}>
   <section className="group-tools" onClick={e=>e.stopPropagation()}>
    <header><div><strong>Group tools</strong><span>Customize, manage members, and moderate groups</span></div><button onClick={()=>setOpen(false)}><X size={18}/></button></header>
    <div className="group-tools-body">
     <aside>{groups.length===0?<div className="group-empty">No groups available.</div>:groups.map(g=><button key={g.id} className={g.id===selectedId?'active':''} onClick={()=>setSelectedId(g.id)}><span>{g.icon||'👥'}</span><b>{g.name}</b><small>{g.members.length} members</small></button>)}<div className="group-join"><input value={inviteCode} onChange={e=>setInviteCode(e.target.value.toUpperCase())} placeholder="Invite code"/><button onClick={requestJoin} disabled={busy}>Request to join</button></div></aside>
     <main>{!group?<div className="group-empty">Select a group.</div>:<>
      <nav>{[['members','Members',Users],['customize','Customize',Shield],['invites','Invites',UserPlus],['pins','Pinned',Pin],['announcements','Announcements',Megaphone]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={15}/>{label}</button>)}</nav>
      {notice&&<div className="group-notice">{notice}</div>}
      {tab==='members'&&<div className="group-panel"><h3>Members</h3>{isAdmin&&<div className="group-add-row"><input value={memberCode} onChange={e=>setMemberCode(e.target.value)} placeholder="12-character User ID"/><button onClick={addMember} disabled={busy}>Add</button></div>}<div className="group-list">{group.members.map(m=><div className="group-row" key={m.auth0_sub}><div><b>{m.display_name||m.user_code}</b><span>{m.user_code} · {m.role}</span></div>{isAdmin&&m.auth0_sub!==user?.sub&&<div className="group-actions">{m.role==='member'?<button onClick={()=>setRole(m,'admin')}>Promote</button>:m.role==='admin'?<button onClick={()=>setRole(m,'member')}>Demote</button>:null}{m.role!=='owner'&&<button onClick={()=>removeMember(m)}>Remove</button>}</div>}</div>)}</div>{requests.length>0&&<><h3>Pending join requests</h3>{requests.map(r=><div className="group-row" key={r.id}><div><b>{r.profile?.display_name||r.requester_sub}</b><span>{r.profile?.user_code||'Unknown user'}</span></div><div className="group-actions"><button onClick={()=>resolveRequest(r,true)} disabled={busy}>Approve</button><button onClick={()=>resolveRequest(r,false)} disabled={busy}>Reject</button></div></div>)}</>}</div>}
      {tab==='customize'&&<div className="group-panel"><h3>Group customization</h3><label>Group name<input value={newName} onChange={e=>setNewName(e.target.value)} maxLength={80}/></label><button onClick={saveName} disabled={busy||!isAdmin}>Save name</button><label>Group icon<input value={newIcon} onChange={e=>setNewIcon(e.target.value)} maxLength={8} placeholder="👥"/></label><button onClick={saveIcon} disabled={busy||!isAdmin}>Save icon</button><p className="muted">The icon is a short emoji/text label stored as group metadata.</p></div>}
      {tab==='invites'&&<div className="group-panel"><h3>Invite codes</h3>{isAdmin&&<><label>Max uses<input type="number" min="1" value={maxUses} onChange={e=>setMaxUses(e.target.value)}/></label><label>Expiration<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label><button onClick={createInvite} disabled={busy}>Generate invite code</button>{inviteCode&&<div className="generated-code">{inviteCode}</div>}</>}{invites.map(i=><div className="group-row" key={i.id}><div><b>{i.code}</b><span>{i.uses}/{i.max_uses} uses{ i.expires_at?` · expires ${new Date(i.expires_at).toLocaleString()}`:''}</span></div></div>)}</div>}
      {tab==='pins'&&<div className="group-panel"><h3>Pinned messages</h3>{pins.length===0?<p className="muted">No pinned messages.</p>:pins.map(p=><div className="group-row" key={p.message_id}><div><b>{p.message_type==='file'?'Attachment':'Pinned message'}</b><span>{new Date(p.created_at).toLocaleString()}</span></div>{isAdmin&&<button onClick={()=>togglePin(p)}>Unpin</button>}</div>)}{isAdmin&&<><h3>Recent messages</h3>{pinCandidates.map(p=><div className="group-row" key={p.message_id}><div><span>{p.ciphertext?'Encrypted text message':'Message'}</span></div><button onClick={()=>togglePin(p)}>{p.pinned_by?'Unpin':'Pin'}</button></div>)}</>}</div>}
      {tab==='announcements'&&<div className="group-panel"><h3>Admin announcements</h3>{isAdmin&&<><textarea value={announcement} onChange={e=>setAnnouncement(e.target.value)} placeholder="Write an announcement…" rows={4}/><button onClick={postAnnouncement} disabled={busy||!announcement.trim()}>Post announcement</button></>}{announcements.map(a=><AnnouncementItem key={a.id} row={a} decrypt={()=>decryptAnnouncement(a)}/>)}</div>}
     </>}</main>
    </div>
   </section>
  </div>
 </>;
}

function AnnouncementItem({row,decrypt}:{row:Announcement;decrypt:()=>Promise<string>}){const [text,setText]=useState('Decrypting…');useEffect(()=>{void decrypt().then(setText);},[row.id]);return <div className="announcement"><b>{text}</b><span>{new Date(row.created_at).toLocaleString()}</span></div>}
